Program ARQUIVO2 ;
{VERSAO COM ALGUMAS MELHORAS....
FUP QUE LEIA DO TECLADO:
NUMERO=4 CARAC, NOME=35 CARAC, CPF=11 CARAC, DIA E MES=2 CARAC, ANO=4 CARAC e CARGO=2 CARAC
E GERE UM ARQUIVO DE ACESSO SEQUENCIAL "AQUIVO1.TXT" COM TODAS AS INFORMAÇÕES LIDAS, OU SEJA 
UM REGISTRO COM 60 CARAC, NUMERO LIDO = 0, ENCERRA A LEITURA
}
USES TARDENOITE;
VAR REGIS:STRING[60];
    ARQ:TEXT;//NOME LOGICO DO ARQUIVO TIPO TEXTO, JÁ QUE O REGISTRO SERÁ UM STRING[60]
    NUM,ANO:STRING[4];
    DIA,MES,CAR:STRING[2];
    NOME:STRING[35];
    CPF:STRING[11];
    A,B,NI,E:INTEGER;
    TOTC:INTEGER;//PARA GUARDAR O TOTAL DE CARACTERES
Begin
//QUANDO TRABALHAR COM ARQUIVOS, LIGAR O NOME LÓGICO AO FISICO E ABRIR O ARQUIVO...
//E ABRIMOS O ARQUIVO UTILIZANDO O APPEND
   ASSIGN(ARQ,'ARQUIVO1.TXT');
   APPEND(ARQ);
//VALIDAR O NUMERO
   REPEAT
	  WRITE('NUM=>');
    READLN(NUM);
    VAL(NUM,NI,E);//ENTREGA O STRING NUM E RECEBE OS INTEIROS NI e E
    IF (E<>0)THEN
     WRITELN('CARACTER NAO NUMERICO');
   UNTIL(E=0);
//FIM DA VALIDACAO
   WHILE (NI>0) DO
    BEGIN
//GARANTIR QUE O CAMPO NUM TENHA 4 DIGITOS
     TOTC:=LENGTH(NUM);
     FOR A:=1 TO 4 - TOTC DO//LENGTH(NUM) DEVOLVE O TOTAKL DE CARACTRES NO STRING NUM
      INSERT('0',NUM,1);
		 WRITE('NOM=>');
     READLN(NOME);
     NOME:=UPCASE(NOME);//TRANSFORMA STRING EM MAIUSCULO
//GARANTIR QUE O NOME TENHA 35 CARACTERES
		 TOTC:=LENGTH(NOME);
		 FOR A:=TOTC+1 TO 35 DO
		  INSERT(' ',NOME,TOTC+1);
     WRITE('CPF=>');
     READLN(CPF);
     WRITE('DIA=>');
     READLN(DIA);
     WRITE('MES=>');
     READLN(MES);
     WRITE('ANO=>');
		 READLN(ANO);
		 WRITE('CARGO=>');
		 READLN(CAR);
		 REGIS:=NUM+NOME+CPF+DIA+MES+ANO+CAR;
//VALIDAR O NUMERO
     REPEAT
	    WRITE('NUM=>');
      READLN(NUM);
      VAL(NUM,NI,E);//ENTREGA O STRING NUM E RECEBE OS INTEIROS NI e E
      IF (E<>0)THEN
       WRITELN('CARACTER NAO NUMERICO');
     UNTIL(E=0);
//FIM DA VALIDACAO
		END;
	 CLOSE(ARQ);
	 TERMINE; 
End.