Program N06AMANDALIMA ;
  
//Feito por AMANDA CRISTINA DA SILVA DE LIMA

USES TARDENOITE;

var
	regis: string[60];
	ARQ: text; //nome logico do arquivo tipo texto ja que o registro será um string[60]
	NUM, ANO: STRING[4];
	DIA, MES, CARGO: STRING[2];
	NOME: STRING[35];
	CPF: STRING[11];
	A, NI, DI, MI, ANOI, CI, CPFI: INTEGER;
	TOTC, ER: INTEGER;
	RES: BOOLEAN;

Begin
//QUANDO TRABALHAR COM ARQUIVOS, LIGAR O NOME LÓGICO AO FISICO E ABRIR O ARQUIVO...
//E ABRIR O ARQUIVO UTILIZANDO O APPEND
	ASSIGN(ARQ, 'ARQUIVO1.TXT');
	APPEND(ARQ);
	REPEAT //VALIDAÇÃO DO NUM
		WRITE('NUM: ');
		READLN(NUM);
		VAL (NUM, NI, ER);
		IF (ER <> 0) THEN
			WRITELN('CARACTER NÃO NÚMERICO');
	UNTIL(ER = 0);
	WHILE (NI > 0) DO
		BEGIN
		//GARANTIR QUE O CAMPO NUM TENHA 4 DÍGITOS
		TOTC:= LENGTH(NUM);
			FOR A:= 1 TO 4 - TOTC DO
				INSERT('0', NUM, 1);
			WRITE('NOME: ');
			READLN(NOME);
			NOME := UPCASE(NOME);
			TOTC := LENGTH(NOME);
			//GARANTIR QUE O CAMPO NOME TENHA 35 CARACTERES
			FOR A:= TOTC + 1 TO 35 DO
				INSERT(' ', NOME,TOTC + 1); 
			REPEAT 
				WRITE('CPF: ');
				READLN(CPF);
				VAL(CPF, CPFI, ER); 
				IF (ER <> 0) THEN
					WRITELN('CARACTER NÃO NÚMERICO');
				IF (LENGTH(CPF) < 11) THEN  //VALIDAÇÃO PARA NÃO ACEITAR CPF MENOR QUE 11 DÍGITOS
					WRITELN('DIGITE UM CPF COM 11 DIÍGITOS');
			UNTIL (LENGTH(CPF) = 11) AND (ER = 0);
			REPEAT
				REPEAT  //VALIDAÇÃO DO DIA
					WRITE('DIA: ');
					READLN(DIA);
					VAL(DIA, DI, ER);
					IF (ER <> 0) THEN
						WRITELN('CARACTER NÃO NÚMERICO');
				UNTIL(ER = 0);
				//GARATIR QUE DIA TENHA 2 DÍGITOS
				TOTC := LENGTH(DIA);
				FOR A := 1 TO 2 - TOTC DO
					INSERT('0', DIA, 1); 
				REPEAT  //VALIDAÇÃO DO MES
					WRITE('MES: ');
					READLN(MES);
					VAL(MES, MI, ER);
					IF (ER <> 0) THEN
						WRITELN('CARACTER NÃO NÚMERICO');
				UNTIL(ER = 0);
				//GARANTIR QUE MES TENHA 2 DÍGITOS
				TOTC := LENGTH(MES);
				FOR A := 1 TO 2 - TOTC DO
					INSERT('0', MES, 1);
				REPEAT
					WRITE('ANO: ');
					READLN(ANO);
					VAL(ANO, ANOI, ER);
					IF (ER <> 0) THEN
						WRITELN('CARACTER NÃO NÚMERICO');
				UNTIL(ER = 0);
				IF (NOT VALDATA(DI, MI, ANOI)) THEN
					WRITELN ('DATA INVÁLIDA')
			UNTIL(VALDATA(DI, MI, ANOI));
			REPEAT   //VALIDAÇÃO DO CARGO
			WRITE('CARGO: ');
			READLN(CARGO);
			VAL(CARGO, CI, ER);
			IF (ER <> 0) THEN
						WRITELN('CARACTER NÃO NÚMERICO');
			IF (CI < 1) OR (CI > 12) THEN
				WRITELN('DIGITE UM CARGO VÁLIDO ENTRE 1 E 12.')
			UNTIL(ER = 0) AND (CI > 0) AND (CI <= 12);
			//GARANTIR QUE GARGO TENHA 2 DÍGITOS
			TOTC := LENGTH(CARGO);
			FOR A := 1 TO 2 - TOTC DO
				INSERT('0', CARGO, 1);	
			REGIS := NUM + NOME + CPF + DIA + MES + ANO + CARGO;
			WRITELN(ARQ, REGIS);
			REPEAT 
			WRITE('NUM: ');
			READLN(NUM);
			VAL (NUM, NI, ER);
			IF (ER <> 0) THEN
				WRITELN('CARACTER NÃO NÚMERICO');
			UNTIL(ER = 0);
		END;
		CLOSE(ARQ);
		TERMINE;
End.