Program N10AMANDALIMA ;
//FEITO POR AMANDA CRISTINA DA SILVA DE LIMA


USES TARDENOITE;

CONST 
NOMEDOCARGO: ARRAY[1..12] OF STRING = ('ENGANADOR DE CHEFE', 'ENROLADOR DE TRABALHO','PENSADOR','ANALISTA DE SISTEMAS','DEGUSTADOR DE CERVEJA',
'TECNICO EM REDES','CONTADOR DE ESTORIAS','SAI DA AULA ANTES','ACOUGUEIRO LIMPINHO','SEGURANCA DE BANHEIRO','GESTOR DE BORBOLETAS','AGENTE LEVA E TRAZ');


VAR ARQ:FILE OF REGIS;
    REG:REGIS;
    VET:VETOR;
    A,B, I, E, IND, PFI, TOTAL, ORDN, ER, DATAINT, AUX, CARGOA, CARGOB, CARGOC:INTEGER;
    ORDS, NUMS, CARS, CLACICARS, CARSALFA, CARSCLAS, SOMASTR, DATASTR, AUXSTR, CLGSTR: STRING;
    NOTASTR:ARRAY[1..6] OF STRING;
Begin
  ASSIGN(ARQ,'CAND.IND');
  RESET(ARQ);
  REPEAT
	WRITELN('DIGITE PARA ESCOLHER A ORDENAÇÃO DA LISTA');
	WRITELN('[1]Classif. nas vagas em ordem alfabética  [2]Ordem de classificação por cargo  [3]Ordem de classificação geral');
	READLN(ORDS);       
	VAL(ORDS, ORDN, ER);
	IF (ER <> 0) THEN
		WRITELN('CARACTER NÃO NÚMERICO')
	ELSE
		IF (ORDN >  3) OR (ORDN < 1) THEN
			WRITELN('OPÇÃO INVÁLIDA');
	WRITELN;
	UNTIL (ER = 0) AND (ORDN < 4) AND (ORDN > 0);
  WHILE (NOT EOF(ARQ)) DO
   BEGIN
    READ(ARQ,REG);
    IND:=IND+1;
    VET[IND].PF:=PFI; //COLOCA A POSICAO FISICA NO VETOR   
    IF (ORDS = '1') AND (REG.CCL <> 0) THEN 
			BEGIN 
    		STR(REG.CCL:4, CARSCLAS);
    		VET[IND].CC:=CARSCLAS + REG.NOME;   
			//ACESSAR CAMPO CONCATENADO COM CCL(STRING) + NOME
    	END
    ELSE
   	 IF (ORDS = '2') THEN
   	 	BEGIN
   	 		STR(REG.CAR:4, CARS); 
   	 		STR(REG.CLC:4, CLACICARS); 
    		VET[IND].CC:=CARS + CLACICARS;
			//ACESSAR CAMPO CONCATENADO CARGO + CLC EM STRING
    	END		
     ELSE   
     	BEGIN
   	   	STR(REG.CLG:4, CLGSTR);
     		VET[IND].CC:=CLGSTR 
			//ACESSAR CAMPO CPF
     	END;
    PFI:=PFI+1;
   END;
//MONTADO O VETOR ORDENAMOS...
  WRITELN('LIDOS=',IND:5,' REGISTROS');
  WRITELN('ORDENANDO... AGUARDE');
  TOTAL:=IND;
	ORDEM(VET,TOTAL);
  WRITELN('ENTER PARA CONTINUAR');
  READLN; 
  
  
  CARGOA:=0;
  CARGOB:=0;
   
//MOSTRA O CONTEUDO DO ARQUIVO USANDO COMO REFERENCIA O CAMPO PF, DO VETOR ORDENADO
   FOR B:=1 TO TOTAL DO
	 BEGIN
	  SEEK(ARQ,VET[B].PF);//POSICIONA NO ARQ NA POSICAO INDICADA PELO CAMPO pf DO VETOR ORDENADO
		READ(ARQ,REG);
//LINHA DETALHE
		IF (ORDS = '1') AND (REG.CCL <> 0) THEN
		BEGIN 
    	IF(REG.CAR <> CARGOA) THEN
    		BEGIN
    			CARGOA := REG.CAR;   
          READLN;
     			CLRSCR; 
					WRITELN;
    		  WRITELN('CURSO:', CARGOA,' ',NOMEDOCARGO[CARGOA]);
					WRITELN;
	      	WRITELN('  ORD NUM N O M E                              NASCIMENTO CAR');
	   	  END;	
			WRITELN(B:5,REG.NUM:5,' ',REG.NOME,' ',REG.DATA.DIA,'/',REG.DATA.MES,'/',REG.DATA.ANO, REG.CAR:3);
		END 
		ELSE
			IF (ORDS = '2') THEN
				BEGIN
				  IF(REG.CAR <> CARGOB) THEN
    				BEGIN
    			 	 CARGOB := REG.CAR;   
             READLN;
     				 CLRSCR;
     				 WRITELN;
    		  	 WRITELN('CURSO:', CARGOB,' ',NOMEDOCARGO[CARGOB]);
		    	   WRITELN;
      			 WRITELN('  ORD INSC N O M E                               SOM   N4   N5   N3   N2   N6   N1 NASCIMENTO CAR  OBERVAÇÃO');
    			  END;	
					WRITE(B:5,REG.NUM:5,' ',REG.NOME,' ',REG.SOM:5,' ',REG.NOTAS[4]:4,' ',REG.NOTAS[5]:4,' ',REG.NOTAS[3]:4,' ',REG.NOTAS[2]:4,' ',
					REG.NOTAS[6]:4,' ',REG.NOTAS[1]:4,' ');
					WRITE(REG.DATA.DIA,'/',REG.DATA.MES,'/',REG.DATA.ANO, REG.CAR:3);
					IF (REG.CCL <> 0) THEN
		  	  WRITELN('  CLASS CAR=',REG.CCL)
		  		ELSE 
		  	  WRITELN;
				END 
			ELSE
				IF (ORDS = '3') THEN
				BEGIN
				  IF((B-1) MOD 25 = 0)THEN
    				BEGIN
     				 READLN;
      			 CLRSCR;
		    	   WRITELN;
		    	   WRITELN('RELAÇÃO ORDEM DE CLASSFICAÇÃO GERAL');
		    	   WRITELN;
      			 WRITELN('  ORD INSC N O M E                               SOM   N4   N5   N3   N2   N6   N1 NASCIMENTO CAR  OBERVAÇÃO');
    			  END;	
					WRITE(B:5,REG.NUM:5,' ',REG.NOME,' ',REG.SOM:5,' ',REG.NOTAS[4]:4,' ',REG.NOTAS[5]:4,' ',REG.NOTAS[3]:4,' ',REG.NOTAS[2]:4,' ',
					REG.NOTAS[6]:4,' ',REG.NOTAS[1]:4,' ');
					WRITE(REG.DATA.DIA,'/',REG.DATA.MES,'/',REG.DATA.ANO, REG.CAR:3);
					IF (REG.CCL <> 0) THEN
		  	 	 WRITELN('  CLASS CAR=',REG.CCL)
		  		ELSE 
		  	 	 WRITELN;
				END
	 END;                                   
	TERMINE;  
End.